// Generated by browser-recorder from recording.json. Do not edit.
import { chromium } from 'playwright';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ABORT_EXIT_CODE = 130;
const DEFAULT_WAIT_MS = 10000;
const SCROLL_WORLD = '__browser_recorder_replay';

// Runs inside an isolated world through the DevTools protocol, never in the
// page's own: it is serialized with toString(), so it may not use this file's
// bindings. segments[i] is the chain of element indexes (children, not nodes)
// that leads to the i-th element, each one inside the previous one's iframe.
function scrollInIsolatedWorld(segments, left, top) {
  let scope = document;
  for (let hop = 0; hop < segments.length; hop += 1) {
    let node = scope;
    for (const index of segments[hop]) {
      node = node.children[index];
      if (!node) throw new Error('The element to scroll is no longer in the page');
    }
    if (hop === segments.length - 1) {
      node.scrollTo({ left, top, behavior: 'instant' });
      return;
    }
    scope = node.contentDocument;
    if (!scope) throw new Error('Cannot scroll inside a frame of another origin');
  }
  window.scrollTo({ left, top, behavior: 'instant' });
}

// Where the element sits in its document as child indexes from the root,
// read with Playwright's own selector engine (its utility world), so nothing
// runs in the page. An XPath never crosses a shadow boundary: reaching the
// document root through ancestors proves the element is not inside one.
async function elementPath(locator) {
  const depth = await locator.locator('xpath=ancestor::*').count();
  const rootSelector = 'xpath=ancestor-or-self::*[' + (depth + 1) + '][self::html]';
  if ((await locator.locator(rootSelector).count()) !== 1) {
    throw new Error('Cannot scroll an element inside a shadow tree');
  }
  const indexes = await Promise.all(
    Array.from({ length: depth + 1 }, (_, up) =>
      locator
        .locator('xpath=ancestor-or-self::*[' + (up + 1) + ']/preceding-sibling::*')
        .count(),
    ),
  );
  return indexes.reverse();
}

function createDeferred() {
  const deferred = {};
  deferred.promise = new Promise((resolve, reject) => {
    deferred.resolve = resolve;
    deferred.reject = reject;
  });
  // A failure may land before anyone awaits it; it is still reported on await.
  deferred.promise.catch(() => {});
  return deferred;
}

function withTimeout(promise, ms, message) {
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => reject(new Error(message)), ms);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(timer));
}

function createRuntime(context, options = {}) {
  const nextPageTimeoutMs = options.nextPageTimeoutMs ?? DEFAULT_WAIT_MS;
  const fileChooserTimeoutMs = options.fileChooserTimeoutMs ?? DEFAULT_WAIT_MS;
  const elementTimeoutMs = options.elementTimeoutMs ?? DEFAULT_WAIT_MS;
  const filesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), 'files');
  const openedPages = [];
  const pageWaiters = [];
  const fileOutcomes = new Map();
  let startedAt = performance.now();
  let currentStep = null;
  let isFinished = false;

  const elapsed = () => Math.round(performance.now() - startedAt);
  const print = (line) => process.stdout.write(line + '\n');
  const release = () => {
    isFinished = true;
    process.stdin.destroy();
  };
  const outcomeFor = (index) => {
    if (!fileOutcomes.has(index)) fileOutcomes.set(index, createDeferred());
    return fileOutcomes.get(index);
  };

  function handlePage(page) {
    const waiter = pageWaiters.shift();
    if (waiter) waiter(page);
    else openedPages.push(page);
  }

  async function answerDialog(queue, dialog) {
    const next = queue.shift();
    if (next && next.action === 'accept') {
      await dialog.accept(next.promptText ?? undefined);
    } else {
      await dialog.dismiss();
    }
  }

  async function chooseFiles(queue, chooser) {
    const next = queue.shift();
    if (!next) return;
    const outcome = outcomeFor(next.index);
    // A recorded name is data: it may only point inside the files directory.
    const missing = next.fileNames.find(
      (name) => path.basename(name) !== name || !existsSync(path.join(filesDir, name)),
    );
    if (missing !== undefined) {
      outcome.reject(new Error('Recorded file not found: files/' + missing));
      return;
    }
    try {
      await chooser.setFiles(next.fileNames.map((name) => path.join(filesDir, name)));
      outcome.resolve();
    } catch (error) {
      outcome.reject(error);
    }
  }

  // The frames that host each element of the chain, the page's main frame first.
  async function framesAndPaths(page, chain) {
    const frames = [page.mainFrame()];
    const paths = [];
    for (const [position, locator] of chain.entries()) {
      const handle = await locator.elementHandle({ timeout: elementTimeoutMs });
      try {
        paths.push(await elementPath(locator));
        if (position < chain.length - 1) {
          const frame = await handle.contentFrame();
          if (!frame) throw new Error('The element that should hold a frame is not an iframe');
          frames.push(frame);
        }
      } finally {
        await handle.dispose();
      }
    }
    return { frames, paths };
  }

  // The deepest frame with a DevTools session of its own: the page's, unless a
  // cross-origin frame lives in another process and the target is inside it.
  async function sessionFor(page, frames) {
    for (let depth = frames.length - 1; depth > 0; depth -= 1) {
      try {
        return { depth, session: await context.newCDPSession(frames[depth]) };
      } catch {
        // Same process as its parent: the parent's session reaches it.
      }
    }
    return { depth: 0, session: await context.newCDPSession(page) };
  }

  async function scrollInWorld(page, chain, [left, top]) {
    const { frames, paths } = await framesAndPaths(page, chain);
    const { depth, session } = await sessionFor(page, frames);
    try {
      const { frameTree } = await session.send('Page.getFrameTree');
      const { executionContextId } = await session.send('Page.createIsolatedWorld', {
        frameId: frameTree.frame.id,
        worldName: SCROLL_WORLD,
      });
      const { exceptionDetails } = await session.send('Runtime.callFunctionOn', {
        executionContextId,
        functionDeclaration: scrollInIsolatedWorld.toString(),
        arguments: [{ value: paths.slice(depth) }, { value: left }, { value: top }],
        returnByValue: true,
      });
      if (exceptionDetails) {
        const description = exceptionDetails.exception?.description ?? exceptionDetails.text;
        throw new Error(description.split('\n')[0].replace(/^Error: /, ''));
      }
    } finally {
      await session.detach().catch(() => {});
    }
  }

  return {
    scrollTo: scrollInWorld,
    start() {
      startedAt = performance.now();
      context.on('page', handlePage);
    },
    async at(offsetMs) {
      const remaining = startedAt + offsetMs - performance.now();
      if (remaining > 0) await new Promise((resolve) => setTimeout(resolve, remaining));
    },
    mark(index) {
      currentStep = index;
      print('::step ' + index + ' ' + elapsed());
    },
    done() {
      print('::done ' + elapsed());
      release();
    },
    fail(error) {
      const message = error instanceof Error ? error.message : String(error);
      print('::error ' + (currentStep ?? '-') + ' ' + JSON.stringify(message));
      process.exitCode = 1;
      release();
    },
    nextPage() {
      const page = openedPages.shift();
      if (page) return Promise.resolve(page);
      const arrival = new Promise((resolve) => pageWaiters.push(resolve));
      return withTimeout(arrival, nextPageTimeoutMs, 'Timed out waiting for the new tab to open');
    },
    expectDialogs(page, entries) {
      const queue = [...entries];
      page.on('dialog', (dialog) => answerDialog(queue, dialog));
    },
    expectFiles(page, entries) {
      const queue = [...entries];
      page.on('filechooser', (chooser) => chooseFiles(queue, chooser));
    },
    filesSet(index) {
      const message = 'Timed out waiting for the file chooser of step ' + index;
      return withTimeout(outcomeFor(index).promise, fileChooserTimeoutMs, message);
    },
    onAbort(handler) {
      let buffer = '';
      const abort = () => {
        if (isFinished) return;
        isFinished = true;
        Promise.resolve()
          .then(handler)
          .catch(() => {})
          .finally(() => process.exit(ABORT_EXIT_CODE));
      };
      process.stdin.setEncoding('utf8');
      process.stdin.on('data', (chunk) => {
        buffer += chunk;
        const lines = buffer.split('\n');
        buffer = lines.pop();
        if (lines.some((line) => line.trim() === 'abort')) abort();
      });
      process.stdin.on('end', abort);
    },
  };
}

const browser = await chromium.launch({ headless: process.env.BROWSER_RECORDER_HEADLESS === '1' });
const context = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const rt = createRuntime(context);
rt.onAbort(() => browser.close());
try {
  const page1 = await context.newPage();
  rt.start();
  await rt.at(0); rt.mark(0);
  await rt.at(0); rt.mark(1);
  await page1.goto("https://example.com/");
  await rt.at(400); rt.mark(2);
  await page1.locator("nav > .menu").nth(2).hover();
  await rt.at(900); rt.mark(3);
  await page1.getByRole("button", { name: "Save", exact: true }).click();
  await rt.at(1500); rt.mark(4);
  await page1.waitForURL((url) => url.origin + url.pathname === "https://example.com/saved");
  await rt.at(2100); rt.mark(5);
  await page1.getByLabel("Email", { exact: true }).fill("ana@example.com");
  await rt.at(2600); rt.mark(6);
  await page1.getByLabel("Email", { exact: true }).press("Control+A");
  await rt.at(2900); rt.mark(7);
  await page1.keyboard.press("Escape");
  await rt.at(3200); rt.mark(8);
  await page1.getByLabel("Accept", { exact: true }).setChecked(true);
  await rt.at(3500); rt.mark(9);
  await page1.locator("select#size").selectOption(["m", "l"]);
  await rt.at(4000); rt.mark(10);
  await rt.scrollTo(page1, [], [0, 640]);
  await rt.at(4400); rt.mark(11);
  await page1.getByRole("button", { name: "Save", exact: true }).dblclick({ modifiers: ["Shift"] });
  await rt.at(5000); rt.mark(12);
  await page1.reload();
  await rt.at(5600); rt.mark(13);
  await page1.goBack();
  await rt.at(6100); rt.mark(14);
  await page1.goForward();
  rt.done();
} catch (error) { rt.fail(error); } finally { await browser.close(); }
