// Generated by browser-recorder from recording.json. Do not edit.
// Recorded with: brave, managed profile.
import { chromium } from 'patchright';
import { existsSync, mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ABORT_EXIT_CODE = 130;
const ABORT_SIGNALS = process.platform === 'win32' ? ['SIGINT', 'SIGTERM', 'SIGBREAK'] : ['SIGINT', 'SIGTERM'];
const DEFAULT_WAIT_MS = 10000;
const SCROLL_WORLD = '__browser_recorder_replay';
const LAUNCH_TIMEOUT_MS = 30000;
const TEMP_PROFILE_PREFIX = 'browser-recorder-profile-';
const REMOVE_RETRIES = 10;
const REMOVE_RETRY_DELAY_MS = 100;
// The engine's own defaults that keep it away from the real keychain.
const KEYCHAIN_SWITCHES = ['--use-mock-keychain', '--password-store=basic'];
// The only argument the environment may add: Chromium's own profile names.
const PROFILE_ARGUMENT = /^--profile-directory=(?:Default|Profile \d{1,4})$/u;

// Same rules as the recorder (launch-arguments.ts): a real window keeps the
// browser's own metrics and only asks for a size; emulated metrics stay for
// recordings made with them.
function buildLaunchOptions(display, target) {
  const isWindow = display.kind === 'window';
  return {
    viewport: isWindow ? null : { width: display.width, height: display.height },
    args: [
      ...(isWindow ? ['--window-size=' + display.width + ',' + display.height] : []),
      ...target.browserArgs,
    ],
    ignoreDefaultArgs: target.shouldUseRealKeychain ? KEYCHAIN_SWITCHES : undefined,
    executablePath: target.executablePath ?? undefined,
  };
}

// Environment variables are data: anything but a profile directory name is
// dropped, so a hostile value cannot add a flag such as a debugging port.
function readBrowserArgs(text) {
  if (!text) return [];
  try {
    const parsed = JSON.parse(text);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter((arg) => typeof arg === 'string' && PROFILE_ARGUMENT.test(arg));
  } catch {
    return [];
  }
}

// A browser that is not installed here falls back to the bundled Chromium.
function readExecutablePath(value) {
  if (!value) return null;
  if (existsSync(value)) return value;
  process.stderr.write('Browser not found: ' + value + '. Using the bundled Chromium.\n');
  return null;
}

function readLaunchTarget(env) {
  return {
    executablePath: readExecutablePath(env.BROWSER_RECORDER_EXECUTABLE_PATH),
    userDataDir: env.BROWSER_RECORDER_USER_DATA_DIR || null,
    browserArgs: readBrowserArgs(env.BROWSER_RECORDER_BROWSER_ARGS),
    shouldUseRealKeychain: env.BROWSER_RECORDER_REAL_KEYCHAIN === '1',
  };
}

// Launches on the profile the environment names, or on a temporary one that
// close() removes. close() may be called more than once.
// Same policy as the app (browser-directory-removal.ts): a browser that has
// just exited can hold a profile file for a moment on Windows.
function removeTemporaryDir(directory) {
  rmSync(directory, {
    recursive: true,
    force: true,
    maxRetries: REMOVE_RETRIES,
    retryDelay: REMOVE_RETRY_DELAY_MS,
  });
}

async function openContext(chromium, display, env = process.env) {
  const target = readLaunchTarget(env);
  const temporaryDir = target.userDataDir
    ? null
    : mkdtempSync(path.join(os.tmpdir(), TEMP_PROFILE_PREFIX));
  const context = await chromium
    .launchPersistentContext(target.userDataDir ?? temporaryDir, {
      headless: env.BROWSER_RECORDER_HEADLESS === '1',
      timeout: LAUNCH_TIMEOUT_MS,
      // The script owns Ctrl+C and SIGTERM (see onAbort): the engine's own
      // handlers would kill the browser without removing a temporary profile.
      handleSIGINT: false,
      handleSIGTERM: false,
      ...buildLaunchOptions(display, target),
    })
    .catch((error) => {
      if (temporaryDir) removeTemporaryDir(temporaryDir);
      throw error;
    });
  let isClosed = false;
  const close = async () => {
    if (isClosed) return;
    isClosed = true;
    try {
      await context.close();
    } finally {
      if (temporaryDir) removeTemporaryDir(temporaryDir);
    }
  };
  return { context, close };
}

const DEFAULT_DELAY = { minMs: 250, maxMs: 900 };
const MAX_DELAY_MS = 60000;
const KEY_DELAY_DIVISOR = 10;
const SEED_PATTERN = /^\d{1,10}$/u;
const RANGE_PATTERN = /^(\d{1,5})-(\d{1,5})$/u;
const UINT32_RANGE = 4294967296;

// Small, fast and seedable: the same seed always gives the same sequence.
function mulberry32(seed) {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let mixed = Math.imul(state ^ (state >>> 15), state | 1);
    mixed ^= mixed + Math.imul(mixed ^ (mixed >>> 7), mixed | 61);
    return ((mixed ^ (mixed >>> 14)) >>> 0) / UINT32_RANGE;
  };
}

// A seed is data: only up to ten digits count, anything else is random.
function readSeed(text) {
  if (typeof text === 'string' && SEED_PATTERN.test(text)) return Number(text) >>> 0;
  return globalThis.crypto.getRandomValues(new Uint32Array(1))[0];
}

function readDelayRange(text) {
  const match = typeof text === 'string' ? RANGE_PATTERN.exec(text) : null;
  if (!match) return DEFAULT_DELAY;
  const minMs = Number(match[1]);
  const maxMs = Number(match[2]);
  return minMs <= maxMs && maxMs <= MAX_DELAY_MS ? { minMs, maxMs } : DEFAULT_DELAY;
}

// Any mode but "human" is recorded, so an unknown value never slows a replay.
function createTiming(env, sleep) {
  const isHuman = env.BROWSER_RECORDER_TIMING === 'human';
  const delay = readDelayRange(env.BROWSER_RECORDER_HUMAN_DELAY);
  const random = mulberry32(readSeed(env.BROWSER_RECORDER_SEED));
  const draw = (minMs, maxMs) => minMs + Math.floor(random() * (maxMs - minMs + 1));
  let hasStarted = false;
  return {
    isHuman,
    delay,
    // The first action starts at once; a follow-up only observes a
    // consequence, so it neither waits nor counts as an action.
    async beforeStep({ isFollowUp }) {
      if (!isHuman || isFollowUp) return;
      const isDue = hasStarted;
      hasStarted = true;
      if (isDue) await sleep(draw(delay.minMs, delay.maxMs));
    },
    async keyPause() {
      const minMs = Math.floor(delay.minMs / KEY_DELAY_DIVISOR);
      const maxMs = Math.floor(delay.maxMs / KEY_DELAY_DIVISOR);
      await sleep(draw(minMs, maxMs));
    },
  };
}

// Recorded mode sets the value at once. Human mode types it key by key, one
// code point at a time, and then makes sure the field holds the exact value:
// masked, date and contenteditable fields may not take typed text as is.
async function fillField(locator, value, timing) {
  if (!timing.isHuman) return locator.fill(value);
  await locator.fill('');
  for (const key of Array.from(value)) {
    await locator.pressSequentially(key);
    await timing.keyPause();
  }
  const typed = await locator.inputValue().catch(() => null);
  if (typed !== value) await locator.fill(value);
}

// The three functions below run inside an isolated world through the
// DevTools protocol, never in the page's own: they are serialized with
// toString(), so they may not use this file's bindings.
function scrollWindowInIsolatedWorld(left, top) {
  window.scrollTo({ left, top, behavior: 'instant' });
}

// Waits, on the window, for one event that Patchright dispatches at the
// element to scroll. A composed event reaches the window from inside any open
// shadow root, and its path names the real element, so no path of child
// indexes, which cannot cross a shadow boundary, is needed.
function armScrollProbe(type, left, top) {
  const state = { scrolled: false, error: '' };
  const handler = (event) => {
    window.removeEventListener(type, handler, true);
    const [target] = event.composedPath();
    if (!(target instanceof Element)) {
      state.error = 'The element to scroll is not reachable';
      return;
    }
    target.scrollTo({ left, top, behavior: 'instant' });
    state.scrolled = true;
  };
  window.addEventListener(type, handler, true);
  window[Symbol.for(type)] = { state, handler };
}

function readScrollProbe(type) {
  const probe = window[Symbol.for(type)];
  if (!probe) return { scrolled: false, error: '' };
  window.removeEventListener(type, probe.handler, true);
  delete window[Symbol.for(type)];
  return probe.state;
}

const NAVIGATION_TIMEOUT_MS = 30000;
const QUIET_WINDOW_MS = 500;
const SETTLE_CAP_MS = 5000;
const SETTLE_POLL_MS = 50;
const MS_PER_SECOND = 1000;
// Requests that never touch the network cannot be waited for.
const IGNORED_REQUEST_SCHEMES = ['data:', 'blob:'];

function withTimeout(promise, ms, message) {
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => reject(new Error(message)), ms);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(timer));
}

// The same comparison the recording makes: origin and pathname only.
function originAndPath(url) {
  try {
    const parsed = new URL(url);
    return parsed.origin + parsed.pathname;
  } catch {
    return url;
  }
}

// A log of main-frame navigations. An action arms it; a follow-up then waits
// for the first navigation newer than that, so one that happened before the
// action never counts, even to the same URL the page already shows.
function createNavigationTracker({ timeoutMs, describeStep }) {
  const log = [];
  const consumed = new Set();
  const listeners = new Set();
  let armedSeq = 0;

  const findMatch = (page, expected) =>
    log.find(
      (entry) =>
        entry.page === page &&
        entry.seq > armedSeq &&
        !consumed.has(entry.seq) &&
        originAndPath(entry.url) === expected,
    );

  function arrivalOf(page, expected, check) {
    return new Promise((resolve) => {
      check.run = () => {
        const entry = findMatch(page, expected);
        if (!entry) return;
        consumed.add(entry.seq);
        resolve();
      };
      listeners.add(check);
      check.run();
    });
  }

  return {
    track(page) {
      page.on('framenavigated', (frame) => {
        if (frame !== page.mainFrame()) return;
        log.push({ seq: log.length + 1, page, url: frame.url() });
        for (const check of [...listeners]) check.run();
      });
    },
    arm() {
      armedSeq = log.length;
    },
    async waitFor(page, expected) {
      const check = {};
      const message = 'Timed out waiting for the navigation of step ' + describeStep() + ' to ' + expected;
      try {
        await withTimeout(arrivalOf(page, expected, check), timeoutMs, message);
      } finally {
        listeners.delete(check);
      }
      await page.waitForLoadState('load');
    },
  };
}

function describeCap(capMs, pendingCount) {
  const noun = pendingCount === 1 ? 'request was' : 'requests were';
  return 'Stopped waiting for the network after ' + capMs / MS_PER_SECOND + ' s; ' + pendingCount + ' ' + noun + ' still in flight';
}

// The requests in flight on every page of the context, popups included.
// WebSockets emit no request event, so an open one never blocks quiet.
function createNetworkTracker(context, { quietWindowMs, capMs, pollMs, sleep, print }) {
  const inFlight = new Set();
  let lastActivityAt = performance.now();
  const touch = () => {
    lastActivityAt = performance.now();
  };
  const finish = (request) => {
    if (inFlight.delete(request)) touch();
  };
  const isIgnored = (request) => IGNORED_REQUEST_SCHEMES.some((scheme) => request.url().startsWith(scheme));

  return {
    start() {
      context.on('request', (request) => {
        if (isIgnored(request)) return;
        inFlight.add(request);
        touch();
      });
      context.on('requestfinished', finish);
      context.on('requestfailed', finish);
    },
    async settle() {
      const startedAt = performance.now();
      for (;;) {
        const now = performance.now();
        const isIdle = inFlight.size === 0 && now - Math.max(lastActivityAt, startedAt) >= quietWindowMs;
        if (isIdle) return { isQuiet: true, pendingCount: 0 };
        if (now - startedAt >= capMs) {
          // A count only: URLs may carry tokens.
          print('::warn ' + JSON.stringify(describeCap(capMs, inFlight.size)));
          return { isQuiet: false, pendingCount: inFlight.size };
        }
        await sleep(pollMs);
      }
    },
  };
}

function createSettling(context, options) {
  const navigation = createNavigationTracker({
    timeoutMs: options.navigationTimeoutMs ?? NAVIGATION_TIMEOUT_MS,
    describeStep: options.describeStep,
  });
  const network = createNetworkTracker(context, {
    quietWindowMs: options.quietWindowMs ?? QUIET_WINDOW_MS,
    capMs: options.settleCapMs ?? SETTLE_CAP_MS,
    pollMs: options.settlePollMs ?? SETTLE_POLL_MS,
    sleep: options.sleep,
    print: options.print,
  });
  return {
    start() {
      network.start();
      context.on('page', navigation.track);
      for (const page of context.pages?.() ?? []) navigation.track(page);
    },
    arm: navigation.arm,
    waitForNavigation: navigation.waitFor,
    settle: network.settle,
  };
}

const HOVER_TIMEOUT_MS = 2000;
const MISSING_HOVER_TARGET = 'the target was not found';

// The first line only: the rest of a Patchright error is a call log that
// quotes the page's markup.
function describeSkippedHover(step, error) {
  const reason = error instanceof Error ? error.message : String(error);
  const position = step === null ? '-' : step + 1;
  return 'Skipped the hover of step ' + position + ': ' + reason.split('\n')[0];
}

function createHovering({ timeoutMs, print, describeStep }) {
  return {
    async hover(locator) {
      try {
        if (!locator) throw new Error(MISSING_HOVER_TARGET);
        await locator.hover({ timeout: timeoutMs });
      } catch (error) {
        print('::warn ' + JSON.stringify(describeSkippedHover(describeStep(), error)));
      }
    },
  };
}

function createDeferred() {
  const deferred = {};
  deferred.promise = new Promise((resolve, reject) => {
    deferred.resolve = resolve;
    deferred.reject = reject;
  });
  // A failure may land before anyone awaits it; it is still reported on await.
  deferred.promise.catch(() => {});
  return deferred;
}

function createRuntime(context, options = {}) {
  const nextPageTimeoutMs = options.nextPageTimeoutMs ?? DEFAULT_WAIT_MS;
  const fileChooserTimeoutMs = options.fileChooserTimeoutMs ?? DEFAULT_WAIT_MS;
  const elementTimeoutMs = options.elementTimeoutMs ?? DEFAULT_WAIT_MS;
  const sleep = options.sleep ?? ((ms) => new Promise((resolve) => setTimeout(resolve, ms)));
  const timing = createTiming(options.env ?? process.env, sleep);
  const settling = createSettling(context, {
    ...options,
    sleep,
    print: (line) => process.stdout.write(line + '\n'),
    describeStep: () => currentStep ?? '-',
  });
  const hovering = createHovering({
    timeoutMs: options.hoverTimeoutMs ?? HOVER_TIMEOUT_MS,
    print: (line) => process.stdout.write(line + '\n'),
    describeStep: () => currentStep,
  });
  const filesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), 'files');
  const openedPages = [];
  const pageWaiters = [];
  const fileOutcomes = new Map();
  let startedAt = performance.now();
  let currentStep = null;
  let isFinished = false;

  const elapsed = () => Math.round(performance.now() - startedAt);
  const print = (line) => process.stdout.write(line + '\n');
  const release = () => {
    isFinished = true;
    process.stdin.destroy();
  };
  const outcomeFor = (index) => {
    if (!fileOutcomes.has(index)) fileOutcomes.set(index, createDeferred());
    return fileOutcomes.get(index);
  };

  async function pace(offsetMs, isFollowUp) {
    // Human pacing never reads the recorded offset.
    if (timing.isHuman) return timing.beforeStep({ isFollowUp });
    // A timer may fire a little early: sleep again rather than run the step
    // before its offset.
    let remaining = startedAt + offsetMs - performance.now();
    while (remaining > 0) {
      await sleep(remaining);
      remaining = startedAt + offsetMs - performance.now();
    }
  }

  function handlePage(page) {
    const waiter = pageWaiters.shift();
    if (waiter) waiter(page);
    else openedPages.push(page);
  }

  async function answerDialog(queue, dialog) {
    const next = queue.shift();
    if (next && next.action === 'accept') {
      await dialog.accept(next.promptText ?? undefined);
    } else {
      await dialog.dismiss();
    }
  }

  async function chooseFiles(queue, chooser) {
    const next = queue.shift();
    if (!next) return;
    const outcome = outcomeFor(next.index);
    // A recorded name is data: it may only point inside the files directory.
    const missing = next.fileNames.find(
      (name) => path.basename(name) !== name || !existsSync(path.join(filesDir, name)),
    );
    if (missing !== undefined) {
      outcome.reject(new Error('Recorded file not found: files/' + missing));
      return;
    }
    try {
      await chooser.setFiles(next.fileNames.map((name) => path.join(filesDir, name)));
      outcome.resolve();
    } catch (error) {
      outcome.reject(error);
    }
  }

  // The frames that host each element of the chain, the page's main frame first.
  async function framesOf(page, chain) {
    const frames = [page.mainFrame()];
    for (const locator of chain.slice(0, -1)) {
      const handle = await locator.elementHandle({ timeout: elementTimeoutMs });
      try {
        const frame = await handle.contentFrame();
        if (!frame) throw new Error('The element that should hold a frame is not an iframe');
        frames.push(frame);
      } finally {
        await handle.dispose();
      }
    }
    return frames;
  }

  // The deepest frame with a DevTools session of its own: the page's, unless a
  // cross-origin frame lives in another process and the target is inside it.
  async function sessionFor(page, frames) {
    for (let depth = frames.length - 1; depth > 0; depth -= 1) {
      try {
        return { session: await context.newCDPSession(frames[depth]) };
      } catch {
        // Same process as its parent: the parent's session reaches it.
      }
    }
    return { session: await context.newCDPSession(page) };
  }

  function failureOf({ exceptionDetails }) {
    if (!exceptionDetails) return null;
    const description = exceptionDetails.exception?.description ?? exceptionDetails.text;
    return new Error(description.split('\n')[0].replace(/^Error: /, ''));
  }

  async function call(session, executionContextId, fn, args) {
    const result = await session.send('Runtime.callFunctionOn', {
      executionContextId,
      functionDeclaration: fn.toString(),
      arguments: args.map((value) => ({ value })),
      returnByValue: true,
    });
    const failure = failureOf(result);
    if (failure) throw failure;
    return result.result.value;
  }

  // An isolated world in every frame this session reaches; a frame of another
  // process is not reachable from it and is skipped.
  async function worldsOf(session) {
    const { frameTree } = await session.send('Page.getFrameTree');
    const worlds = [];
    const visit = async (node) => {
      try {
        const { executionContextId } = await session.send('Page.createIsolatedWorld', {
          frameId: node.frame.id,
          worldName: SCROLL_WORLD,
        });
        worlds.push(executionContextId);
      } catch {
        // Not a frame of this session.
      }
      for (const child of node.childFrames ?? []) await visit(child);
    };
    await visit(frameTree);
    return worlds;
  }

  async function scrollElement(session, chain, [left, top]) {
    const type = 'br-scroll-' + globalThis.crypto.randomUUID();
    const worlds = await worldsOf(session);
    for (const world of worlds) await call(session, world, armScrollProbe, [type, left, top]);
    let dispatchError = null;
    try {
      await chain[chain.length - 1].dispatchEvent(
        type,
        { bubbles: true, composed: true },
        { timeout: elementTimeoutMs },
      );
    } catch (error) {
      dispatchError = error;
    }
    const states = [];
    for (const world of worlds) states.push(await call(session, world, readScrollProbe, [type]));
    if (dispatchError) throw dispatchError;
    const failed = states.find((state) => state.error !== '');
    if (failed) throw new Error(failed.error);
    if (!states.some((state) => state.scrolled)) {
      throw new Error('The element to scroll is no longer in the page');
    }
  }

  async function scrollInWorld(page, chain, position) {
    const frames = await framesOf(page, chain);
    const { session } = await sessionFor(page, frames);
    try {
      if (chain.length > 0) return await scrollElement(session, chain, position);
      const [world] = await worldsOf(session);
      await call(session, world, scrollWindowInIsolatedWorld, position);
    } finally {
      await session.detach().catch(() => {});
    }
  }

  return {
    scrollTo: scrollInWorld,
    start() {
      startedAt = performance.now();
      context.on('page', handlePage);
      settling.start();
    },
    waitForNavigation: settling.waitForNavigation,
    settle: settling.settle,
    async at(offsetMs, { isFollowUp = false } = {}) {
      await pace(offsetMs, isFollowUp);
      // The wait for the navigation an action causes starts from here.
      if (!isFollowUp) settling.arm();
    },
    hover: hovering.hover,
    fill: (locator, value) => fillField(locator, value, timing),
    mark(index) {
      currentStep = index;
      print('::step ' + index + ' ' + elapsed());
    },
    done() {
      print('::done ' + elapsed());
      release();
    },
    fail(error) {
      const message = error instanceof Error ? error.message : String(error);
      print('::error ' + (currentStep ?? '-') + ' ' + JSON.stringify(message));
      process.exitCode = 1;
      release();
    },
    nextPage() {
      const page = openedPages.shift();
      if (page) return Promise.resolve(page);
      const arrival = new Promise((resolve) => pageWaiters.push(resolve));
      return withTimeout(arrival, nextPageTimeoutMs, 'Timed out waiting for the new tab to open');
    },
    expectDialogs(page, entries) {
      const queue = [...entries];
      page.on('dialog', (dialog) => answerDialog(queue, dialog));
    },
    expectFiles(page, entries) {
      const queue = [...entries];
      page.on('filechooser', (chooser) => chooseFiles(queue, chooser));
    },
    filesSet(index) {
      const message = 'Timed out waiting for the file chooser of step ' + index;
      return withTimeout(outcomeFor(index).promise, fileChooserTimeoutMs, message);
    },
    onAbort(handler) {
      let buffer = '';
      const abort = () => {
        if (isFinished) return;
        isFinished = true;
        Promise.resolve()
          .then(handler)
          .catch(() => {})
          .finally(() => process.exit(ABORT_EXIT_CODE));
      };
      process.stdin.setEncoding('utf8');
      process.stdin.on('data', (chunk) => {
        buffer += chunk;
        const lines = buffer.split('\n');
        buffer = lines.pop();
        if (lines.some((line) => line.trim() === 'abort')) abort();
      });
      process.stdin.on('end', abort);
      // Ctrl+C reaches this process as well as the parent: close the same way.
      for (const name of ABORT_SIGNALS) process.on(name, abort);
    },
  };
}

const { context, close } = await openContext(chromium, { kind: "window", width: 1280, height: 800 });
const rt = createRuntime(context);
rt.onAbort(close);
try {
  const page1 = context.pages()[0] ?? (await context.newPage());
  rt.start();
  await rt.at(0, { isFollowUp: true }); rt.mark(0);
  await rt.at(0); rt.mark(1);
  await page1.goto("https://example.com/");
  await rt.at(400); rt.mark(2);
  await rt.hover(page1.locator("nav > .menu").nth(2));
  await rt.at(900); rt.mark(3);
  await page1.getByRole("button", { name: "Save", exact: true }).click();
  await rt.at(1500, { isFollowUp: true }); rt.mark(4);
  await rt.waitForNavigation(page1, "https://example.com/saved");
  await rt.at(2100); rt.mark(5);
  await rt.fill(page1.getByLabel("Email", { exact: true }), "ana@example.com");
  await rt.at(2600); rt.mark(6);
  await page1.getByLabel("Email", { exact: true }).press("Control+A");
  await rt.at(2900); rt.mark(7);
  await page1.keyboard.press("Escape");
  await rt.at(3200); rt.mark(8);
  await page1.getByLabel("Accept", { exact: true }).setChecked(true);
  await rt.at(3500); rt.mark(9);
  await page1.locator("select#size").selectOption(["m", "l"]);
  await rt.at(4000); rt.mark(10);
  await rt.scrollTo(page1, [], [0, 640]);
  await rt.at(4400); rt.mark(11);
  await page1.getByRole("button", { name: "Save", exact: true }).dblclick({ modifiers: ["Shift"] });
  await rt.at(5000); rt.mark(12);
  await page1.reload();
  await rt.at(5600); rt.mark(13);
  await page1.goBack();
  await rt.at(6100); rt.mark(14);
  await page1.goForward();
  await rt.settle();
  rt.done();
} catch (error) { rt.fail(error); } finally { await close(); }
