// Generated by browser-recorder from recording.json. Do not edit.
import { chromium } from 'playwright';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ABORT_EXIT_CODE = 130;
const DEFAULT_WAIT_MS = 10000;

function createDeferred() {
  const deferred = {};
  deferred.promise = new Promise((resolve, reject) => {
    deferred.resolve = resolve;
    deferred.reject = reject;
  });
  // A failure may land before anyone awaits it; it is still reported on await.
  deferred.promise.catch(() => {});
  return deferred;
}

function withTimeout(promise, ms, message) {
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => reject(new Error(message)), ms);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(timer));
}

function createRuntime(context, options = {}) {
  const nextPageTimeoutMs = options.nextPageTimeoutMs ?? DEFAULT_WAIT_MS;
  const fileChooserTimeoutMs = options.fileChooserTimeoutMs ?? DEFAULT_WAIT_MS;
  const filesDir = path.join(path.dirname(fileURLToPath(import.meta.url)), 'files');
  const openedPages = [];
  const pageWaiters = [];
  const fileOutcomes = new Map();
  let startedAt = performance.now();
  let currentStep = null;
  let isFinished = false;

  const elapsed = () => Math.round(performance.now() - startedAt);
  const print = (line) => process.stdout.write(line + '\n');
  const release = () => {
    isFinished = true;
    process.stdin.destroy();
  };
  const outcomeFor = (index) => {
    if (!fileOutcomes.has(index)) fileOutcomes.set(index, createDeferred());
    return fileOutcomes.get(index);
  };

  function handlePage(page) {
    const waiter = pageWaiters.shift();
    if (waiter) waiter(page);
    else openedPages.push(page);
  }

  async function answerDialog(queue, dialog) {
    const next = queue.shift();
    if (next && next.action === 'accept') {
      await dialog.accept(next.promptText ?? undefined);
    } else {
      await dialog.dismiss();
    }
  }

  async function chooseFiles(queue, chooser) {
    const next = queue.shift();
    if (!next) return;
    const outcome = outcomeFor(next.index);
    // A recorded name is data: it may only point inside the files directory.
    const missing = next.fileNames.find(
      (name) => path.basename(name) !== name || !existsSync(path.join(filesDir, name)),
    );
    if (missing !== undefined) {
      outcome.reject(new Error('Recorded file not found: files/' + missing));
      return;
    }
    try {
      await chooser.setFiles(next.fileNames.map((name) => path.join(filesDir, name)));
      outcome.resolve();
    } catch (error) {
      outcome.reject(error);
    }
  }

  return {
    start() {
      startedAt = performance.now();
      context.on('page', handlePage);
    },
    async at(offsetMs) {
      const remaining = startedAt + offsetMs - performance.now();
      if (remaining > 0) await new Promise((resolve) => setTimeout(resolve, remaining));
    },
    mark(index) {
      currentStep = index;
      print('::step ' + index + ' ' + elapsed());
    },
    done() {
      print('::done ' + elapsed());
      release();
    },
    fail(error) {
      const message = error instanceof Error ? error.message : String(error);
      print('::error ' + (currentStep ?? '-') + ' ' + JSON.stringify(message));
      process.exitCode = 1;
      release();
    },
    nextPage() {
      const page = openedPages.shift();
      if (page) return Promise.resolve(page);
      const arrival = new Promise((resolve) => pageWaiters.push(resolve));
      return withTimeout(arrival, nextPageTimeoutMs, 'Timed out waiting for the new tab to open');
    },
    expectDialogs(page, entries) {
      const queue = [...entries];
      page.on('dialog', (dialog) => answerDialog(queue, dialog));
    },
    expectFiles(page, entries) {
      const queue = [...entries];
      page.on('filechooser', (chooser) => chooseFiles(queue, chooser));
    },
    filesSet(index) {
      const message = 'Timed out waiting for the file chooser of step ' + index;
      return withTimeout(outcomeFor(index).promise, fileChooserTimeoutMs, message);
    },
    onAbort(handler) {
      let buffer = '';
      const abort = () => {
        if (isFinished) return;
        isFinished = true;
        Promise.resolve()
          .then(handler)
          .catch(() => {})
          .finally(() => process.exit(ABORT_EXIT_CODE));
      };
      process.stdin.setEncoding('utf8');
      process.stdin.on('data', (chunk) => {
        buffer += chunk;
        const lines = buffer.split('\n');
        buffer = lines.pop();
        if (lines.some((line) => line.trim() === 'abort')) abort();
      });
      process.stdin.on('end', abort);
    },
  };
}

const browser = await chromium.launch({ headless: process.env.BROWSER_RECORDER_HEADLESS === '1' });
const context = await browser.newContext({ viewport: { width: 1280, height: 800 } });
const rt = createRuntime(context);
rt.onAbort(() => browser.close());
try {
  const page1 = await context.newPage();
  rt.expectDialogs(page1, [{ index: 3, action: "accept", promptText: "Ana" }]);
  rt.expectFiles(page1, [{ index: 5, fileNames: ["report.pdf", "photo.png"] }]);
  rt.start();
  await rt.at(0); rt.mark(0);
  await rt.at(0); rt.mark(1);
  await page1.goto("https://example.com/upload");
  await rt.at(500); rt.mark(2);
  await page1.frameLocator("iframe#outer").frameLocator("iframe[name=\"inner\"]").getByTestId("inner-button").click({ button: "right", modifiers: ["Alt"] });
  await rt.at(800); rt.mark(3);
  await rt.at(1200); rt.mark(4);
  await page1.getByText("Choose file", { exact: true }).click();
  await rt.at(1300); rt.mark(5);
  await rt.filesSet(5);
  await rt.at(2000); rt.mark(6);
  await page1.getByText("Open help", { exact: true }).click({ button: "middle" });
  await rt.at(2100); rt.mark(7);
  const page2 = await rt.nextPage();
  rt.expectDialogs(page2, [{ index: 8, action: "dismiss", promptText: null }]);
  await rt.at(2600); rt.mark(8);
  await rt.at(3000); rt.mark(9);
  await page2.getByPlaceholder("Drag me", { exact: true }).dragTo(page2.locator("nav > .menu").nth(2));
  await rt.at(3500); rt.mark(10);
  await page2.close();
  await rt.at(4000); rt.mark(11);
  const page3 = await context.newPage();
  await rt.at(4500); rt.mark(12);
  await page3.locator("nav > .menu").nth(2).evaluate((element, [x, y]) => { element.scrollTo(x, y); }, [3, 9]);
  await rt.at(4600); rt.mark(13);
  await page3.goto("https://example.com/done");
  rt.done();
} catch (error) { rt.fail(error); } finally { await browser.close(); }
