import {
  BROWSER_IDS,
  type BrowserChoice,
} from '../../shared/domain/browser-choice.ts';
import type { Recording } from '../../shared/domain/recording.ts';
import type { RecordingEvent } from '../../shared/domain/recording-event.ts';
import { jsNumber, jsString } from './js-literal.ts';
import { renderPageHooks } from './render-page-hooks.ts';
import { renderStep } from './render-step.ts';
import { scriptPrelude } from './script-prelude.ts';

const INDENT = '  ';
const FIRST_PAGE = 'page1';

const UNKNOWN_BROWSER = 'unknown browser';

/**
 * The id is data and a hand-edited file may carry anything, so only a known
 * id is printed: nothing recorded can leave the comment.
 */
function describeBrowser(browser: BrowserChoice): string {
  const isKnown = (BROWSER_IDS as readonly string[]).includes(
    browser.browserId,
  );
  return `${isKnown ? browser.browserId : UNKNOWN_BROWSER}, ${browser.profileMode} profile`;
}

function renderDisplay(display: Recording['display']): string {
  const { kind, width, height } = display;
  return `{ kind: ${jsString(kind)}, width: ${jsNumber(width)}, height: ${jsNumber(height)} }`;
}

function renderHeader(recording: Recording): string[] {
  return [
    '// Generated by browser-recorder from recording.json. Do not edit.',
    `// Recorded with: ${describeBrowser(recording.browser)}.`,
    "import { chromium } from 'patchright';",
    scriptPrelude,
    `const { context, close } = await openContext(chromium, ${renderDisplay(recording.display)});`,
    'const rt = createRuntime(context);',
    'rt.onAbort(close);',
  ];
}

function renderStepBlock(
  event: RecordingEvent,
  index: number,
  events: readonly RecordingEvent[],
): string[] {
  const statements = renderStep(event, index);
  const hooks =
    event.kind === 'page-opened' && event.pageId !== FIRST_PAGE
      ? renderPageHooks(event.pageId, events)
      : [];
  return [
    `await rt.at(${jsNumber(event.offsetMs)}); rt.mark(${jsNumber(index)});`,
    ...statements,
    ...hooks,
  ];
}

function renderBody(recording: Recording): string[] {
  const { events } = recording;
  return [
    `const ${FIRST_PAGE} = context.pages()[0] ?? (await context.newPage());`,
    ...renderPageHooks(FIRST_PAGE, events),
    'rt.start();',
    ...events.flatMap((event, index) => renderStepBlock(event, index, events)),
    'rt.done();',
  ];
}

/**
 * Plain Patchright ESM for a recording. Pure and deterministic: no clock, no
 * randomness and no IO, so an unsupported event throws before anything could
 * be written.
 */
export function generateScript(recording: Recording): string {
  const header = renderHeader(recording);
  const body = renderBody(recording).map((line) => `${INDENT}${line}`);
  return [
    ...header,
    'try {',
    ...body,
    '} catch (error) { rt.fail(error); } finally { await close(); }',
    '',
  ].join('\n');
}
