import type { Recording } from '../../shared/domain/recording.ts';
import type { RecordingEvent } from '../../shared/domain/recording-event.ts';
import { jsNumber } from './js-literal.ts';
import { renderPageHooks } from './render-page-hooks.ts';
import { renderStep } from './render-step.ts';
import { scriptPrelude } from './script-prelude.ts';

const INDENT = '  ';
const FIRST_PAGE = 'page1';

function renderHeader(recording: Recording): string[] {
  const { width, height } = recording.viewport;
  return [
    '// Generated by browser-recorder from recording.json. Do not edit.',
    "import { chromium } from 'playwright';",
    scriptPrelude,
    "const browser = await chromium.launch({ headless: process.env.BROWSER_RECORDER_HEADLESS === '1' });",
    `const context = await browser.newContext({ viewport: { width: ${jsNumber(width)}, height: ${jsNumber(height)} } });`,
    'const rt = createRuntime(context);',
    'rt.onAbort(() => browser.close());',
  ];
}

function renderStepBlock(
  event: RecordingEvent,
  index: number,
  events: readonly RecordingEvent[],
): string[] {
  const statements = renderStep(event, index);
  const hooks =
    event.kind === 'page-opened' && event.pageId !== FIRST_PAGE
      ? renderPageHooks(event.pageId, events)
      : [];
  return [
    `await rt.at(${jsNumber(event.offsetMs)}); rt.mark(${jsNumber(index)});`,
    ...statements,
    ...hooks,
  ];
}

function renderBody(recording: Recording): string[] {
  const { events } = recording;
  return [
    `const ${FIRST_PAGE} = await context.newPage();`,
    ...renderPageHooks(FIRST_PAGE, events),
    'rt.start();',
    ...events.flatMap((event, index) => renderStepBlock(event, index, events)),
    'rt.done();',
  ];
}

/**
 * Plain Playwright ESM for a recording. Pure and deterministic: no clock, no
 * randomness and no IO, so an unsupported event throws before anything could
 * be written.
 */
export function generateScript(recording: Recording): string {
  const header = renderHeader(recording);
  const body = renderBody(recording).map((line) => `${INDENT}${line}`);
  return [
    ...header,
    'try {',
    ...body,
    '} catch (error) { rt.fail(error); } finally { await browser.close(); }',
    '',
  ].join('\n');
}
